command_timeout = 1000

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[directory]
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[spack]
symbol = "ğŸ…¢ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

# # Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# format = """
# [î‚¶](#8FBCBB)\
# $username\
# $directory\
# $git_branch\
# $git_status\
# $c\
# $golang\
# $haskell\
# $julia\
# $nodejs\
# $nim\
# $python\
# $rust\
# $time
# $character
# """

# [username]
# show_always = true
# style_user = "fg:#2E3440 bg:#8FBCBB"
# style_root = "fg:#2E3440 bg:#8FBCBB"
# format = '[$user ]($style)'

# [directory]
# read_only = " ï ½"
# style = "fg:#ECEFF4 bg:#3B4252"
# format = "[ $path ]($style)"
# home_symbol = "ï®Ÿ ~"
# truncation_length = 3
# truncate_to_repo = false
# truncation_symbol = "â€¦/"
# fish_style_pwd_dir_length = 1

# [directory.substitutions]
# "Documents" = "ïœ˜ "
# "Downloads" = "ï€™ "
# "Music" = "ï€ "
# "Pictures" = "ï€¾ "
# "oss" = "îˆ "
# "projects" = "ï†œ "

# [fill]
# symbol = "â€¢"
# style = "dimmed #D8DEE9"

# [character]
# success_symbol = " [Î»](bold green)"
# error_symbol = " [Î»](bold red)"

# [aws]
# # symbol = "îŒ½ "
# format = 'on [$symbol($profile )(\($region\) )]($style)'
# style = "bold blue"
# symbol = "ğŸ…° "

# [c]
# symbol = "î˜ "
# style = "bg:#5E81AC"
# format = '[[ $symbol ($version) ](bg:#5E81AC)]($style)'

# [conda]
# symbol = "ï„Œ "

# [docker_context]
# symbol = "ïŒˆ "
# style = "bg:#06969A"
# format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

# [git_branch]
# symbol = "ï˜"
# style = "fg:#ECEFF4 bg:#4C566A"
# format = '[[ $symbol $branch ](fg:#ECEFF4 bg:#4C566A)]($style)'

# [git_status]
# style = "fg:#ECEFF4 bg:#4C566A"
# format = '[[($all_status$ahead_behind )](fg:#ECEFF4 bg:#4C566A)]($style)'

# [golang]
# symbol = "î˜§ "
# style = "bg:#5E81AC"
# format = '[[ $symbol ($version) ](bg:#5E81AC)]($style)'

# [haskell]
# symbol = "î· "
# style = "bg:#5E81AC"
# format = '[[ $symbol ($version) ](bg:#5E81AC)]($style)'

# [julia]
# symbol = "î˜¤ "
# style = "bg:#5E81AC"
# format = '[[ $symbol ($version) ](bg:#5E81AC)]($style)'

# [nodejs]
# symbol = "îœ˜"
# style = "bg:#5E81AC"
# format = '[[ $symbol ($version) ](bg:#5E81AC)]($style)'

# [nim]
# symbol = "ïš¤ "
# style = "bg:#5E81AC"
# format = '[[ $symbol ($version) ](bg:#5E81AC)]($style)'

# [python]
# symbol = "îˆµ "
# style = "bg:#5E81AC"
# format = '[[ $symbol ($version) ](bg:#5E81AC)]($style)'

# [rust]
# symbol = "î¨"
# style = "bg:#5E81AC"
# format = '[[ $symbol ($version) ](bg:#5E81AC)]($style)'

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "fg:#ECEFF4 bg:#3B4252"
# format = '[[ îƒ $time ](bg:#3B4252)]($style)'
